name: CORS Proxy

on:
  push:
    branches: [main]

jobs:
  deploy-proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build proxy
        run: |
          mkdir -p api
          cat > api/proxy.js <<EOF
          export default async function handler(req, res) {
            try {
              const response = await fetch('https://wcz3qr33kmjvzotdqt65efniv40kokon.lambda-url.us-east-2.on.aws', {
                headers: {
                  'Content-Type': 'application/json',
                }
              });

              if (!response.ok) {
                throw new Error(`HTTP error ${response.status}`);
              }

              const data = await response.json();
              res.status(200).json(data);
            } catch (error) {
              console.error('Error fetching data:', error);
              res.status(500).json({ error: 'Failed to fetch data' });
            }
          }
          EOF
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          cname: krish4uu.github.io